#!/bin/sh
if [ -f /var/log/update.script.log ]
then
	sudo apt-get update > /var/log/update.script.log
	sudo apt-get upgrade > /var/log/update.script.log
else
	sudo touch /var/log/update.script.log
	sudo chmod 666 /var/log/update.script.log
	sudo apt-get update > /var/log/update.script.log
	sudo apt-get upgrade > /var/log/update.script.log
fi
